print("Hello World!")
print ('what is your name?')
myname = input()
print('it is good to you {}'.format(myname))
print('the length of your name is:')
print(len(myname))
      
print("what is your age?")
myage = input()
print("you will be {} in a year".format(str(int(myage)+1)))
